version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8888:80"
    depends_on:
      - app
    container_name: forum_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
        - ./:/var/www
    user: "www-data:www-data"
    container_name: forum_app


